version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
    depends_on:
      - build

  build:
    image: node:lts-alpine
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "npm install && npm run build"
